export const newCharacterPersonalDetails = {
  characterName: null,
  gender: null,
  race: null,
  kingdomBirth: null,
  height: null,
  weight: null,
  startingProfession: null,
  religion: null,
  distinctiveFeatures: null,
  movement: 30,
  age: null,
  wealth: null,
  kingdomLoyalty: null,
  kingdomReputations: {
    gartu: "none",
    drishma: "none",
    edneth: "none",
    brelloth: "none",
    portro: "none",
    hobantho: "none",
    crillatha: "none",
    virensa: "none",
    pirates: "none",
    independent: "none",
  },
};
