export const newCharacterPersonalDetails = {
  characterName: "",
  gender: "",
  race: "",
  kingdomBirth: "",
  startingProfession: "",
  religion: "",
  distinctiveFeatures: "",
  movement: 30,
  age: "",
  wealth: "average",
  kingdomLoyalty: "",
  kingdomReputations: {
    gartu: "none",
    drishma: "none",
    edneth: "none",
    brelloth: "none",
    portro: "none",
    hobantho: "none",
    crillatha: "none",
    virensa: "none",
    pirates: "none",
    independent: "none",
  },
};
