export const Strings = {
  race: {
    dwarf: "dwarf",
    elf: "elf",
    human: "human",
  },
  gender: {
    male: "male",
    female: "female",
  },
  kingdom: {
    gartu: "gartu",
    drishma: "drishma",
    edneth: "edneth",
    brelloth: "brelloth",
    portro: "portro",
    hobantho: "hobantho",
    crillatha: "crillatha",
    virensa: "virensa",
    pirate: "pirate",
    independent: "independent",
  },
  religion: {
    theTwelve: "The Twelve",
    theTrinity: "The Trinity",
    theCreatorsChildren: "The Creator's Children",
    theWaterOfLife: "The Water of Life",
  },
  reputation: {
    hero: "Hero",
    love: "Love",
    grateful: "Grateful",
    friendly: "Friendly",
    none: "None",
    aware: "Aware",
    dislike: "Dislike",
    hate: "Hate",
    fear: "Fear",
  },
  characteristic: {
    strength: "Strength",
    constitution: "Constitution",
    size: "Size",
    intelligence: "Intelligence",
    power: "Power",
    dexterity: "Dexterity",
    charisma: "Charisma",
    education: "Education",
  },
  language: {
    basic: "Basic",
    elvish: "Elvish",
    dwarvish: "Dwarvish",
    entish: "Entish",
    troll: "Troll",
    orc: "Orc",
    blackSpeech: "Black Speech",
  },
  skill: {
    combat: {
      brawl: "Brawl",
      dodge: "Dodge",
      grapple: "Grapple",
      meleeWeapon: "Melee Weapon",
      missileWeapon: "Missile Weapon",
      shield: "Shield",
    },
    communication: {
      bargain: "Bargain",
      command: "Command",
      disguise: "Disguise",
      etiquette: "Etiquette",
      fastTalk: "Fast Talk",
      intimidate: "Intimidate",
      langauage: "Language",
      nature: "Nature",
      perform: "Perform",
      persuade: "Persuade",
      teach: "Teach",
    },
    mental: {
      appraise: "Appraise",
      firstAid: "First Aid",
      gaming: "Gaming",
      knowledge: "Knowledge",
      literacy: "Literacy",
      medicine: "Medicine",
      potion: "Potion",
      science: "Science",
      strategy: "Strategy",
      technical: "Technical",
    },
    motorSkills: {
      art: "Art",
      craft: "Craft",
      demolition: "Demoltion",
      fineManipulation: "Fine Manipulation",
      instrument: "Instrument",
      lockpicking: "Lockpicking",
      repair: "Repair",
      sleightOfHand: "Sleight of Hand",
    },
    perception: {
      insight: "Insight",
      listen: "Listen",
      navigate: "Navigate",
      research: "Research",
      sense: "Sense",
      spot: "Spot",
      track: "Track",
    },
    physical: {
      climb: "climb",
      fish: "fish",
      hide: "hide",
      hunt: "hunt",
      jump: "jump",
      liquor: "liquor",
      pilot: "pilot",
      ride: "ride",
      stealth: "stealth",
      swim: "swim",
      throw: "throw",
    },
  },
  weapon: {
    meleeWeapon: { axe: "Axe", sword: "Sword" },
    missileWeapon: { bow: "Bow" },
  },
};

export const Capitalize = (word) => {
  return word?.charAt(0).toUpperCase() + word?.slice(1);
};
